# Generated by Django 2.2.6 on 2019-10-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, upload_to='usuarios/media'),
        ),
    ]
