# Generated by Django 2.2.6 on 2019-11-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191027_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(null=True, upload_to='usuarios/media'),
        ),
    ]
