# Generated by Django 2.2.6 on 2019-10-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
