# Generated by Django 2.2.6 on 2019-10-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missao', '0002_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('utilidade', models.TextField(max_length=400)),
                ('pontos', models.IntegerField()),
                ('isValid', models.BooleanField(default=False)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
