# Generated by Django 2.2.6 on 2019-10-13 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missao', '0003_missoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuariomissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_desistido', models.BooleanField(default=False)),
                ('is_concluido', models.BooleanField(default=False)),
                ('is_ganhador', models.BooleanField(default=False)),
                ('id_missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missao.Missoes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
