# Generated by Django 2.2.6 on 2019-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missao', '0004_usuariomissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='missoes',
            name='foto',
            field=models.ImageField(blank=True, upload_to='noticias'),
        ),
    ]
