# Generated by Django 2.2.6 on 2019-10-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missao', '0005_missoes_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missoes',
            name='foto',
        ),
    ]
